from ROOT import *

f_Data = TFile.Open("../../results/Calo_ra3tight_PhotonHad_Run2011A_uptoRun171106_1.root")
c = TCanvas("", "", 1000, 1000)
c.SetLogy()
for hist in ["pfMET_1", "pfMET_2", "pfMET_3"]:
#for hist in ["tcMET_1", "tcMET_2", "tcMET_3"]:
  Sele = f_Data.Get("StandardPlots_HT_sele/"+hist)
  Anti = f_Data.Get("StandardPlots_HT_cont/"+hist)
  #Sele.Scale(1./Sele.Integral())
  Anti.Scale(Sele.Integral(1,10)/Anti.Integral(1,10))
  error = Double(0.)
  print "Predicted nEvents with 50 < MET < 100: "+str(Anti.IntegralAndError(11,20,error))
  print "Error: "+str(error)
  print "Predicted nEvents with 100 < MET < 150: "+str(Anti.IntegralAndError(21,30,error))
  print "Error: "+str(error)
  print "Predicted nEvents with MET > 150: "+str(Anti.IntegralAndError(31,80, error))
  print "Error: "+str(error)
  print "Observed nEvents with 50 < MET < 100: "+str(Sele.IntegralAndError(11,20,error))
  print "Error: "+str(error)
  print "Observed nEvents with 100 < MET < 150: "+str(Sele.IntegralAndError(21,30,error))
  print "Error: "+str(error)
  print "Observed nEvents with MET > 150: "+str(Sele.IntegralAndError(31,80, error))
  print "Error: "+str(error)
  Anti.SetLineColor(4)
  Anti.SetLineWidth(3)
  Anti.Draw("LP")
  Sele.SetMarkerColor(1)
  Sele.SetMarkerStyle(20)
  Sele.SetLineWidth(3)
  Sele.Draw("EPSAME")
  c.SaveAs("MET/FullRange-"+hist+".png")
  c.SaveAs("MET/FullRange-"+hist+".eps")
  Sele.GetXaxis().SetRangeUser(0., 150.)
  Anti.GetXaxis().SetRangeUser(0., 150.)
  c.SaveAs("MET/UpTo100-"+hist+".png")
  c.SaveAs("MET/UpTo100-"+hist+".eps")
  Sele.SetBinContent(31, Sele.Integral(31,80))
  Anti.SetBinContent(31, Anti.Integral(31,80))
  c.SaveAs("MET/Overflow-"+hist+".png")
  c.SaveAs("MET/Overflow-"+hist+".eps")
