from ROOT import *

gStyle.SetOptStat(0)
file_data = TFile.Open("../../results/Calo_ra3tight_PhotonHad_Run2011A_uptoRun171106_1.root")
file_mc = TFile.Open("../../results/Calo_ra3tight_reweighted_G_TuneZ2_pythia6.root")
hist_data = file_data.Get("StandardPlots_HT_sele/nVertices_all")
hist_data.Scale(1./hist_data.Integral(1,11))
hist_data.SetLineColor(1)
hist_data.SetLineWidth(3)
hist_data.GetYaxis().SetTitle("")
hist_mc = file_mc.Get("StandardPlots_HT_sele/nVertices_all")
hist_mc.Scale(1./hist_mc.Integral(1,11))
hist_mc.SetLineColor(1)
hist_mc.SetLineWidth(3)
hist_mc.GetYaxis().SetTitle("")
c = TCanvas("canvas","name",1200,1200)
hist_mc.Draw()
c.SaveAs("nVertices-MC-reweighted.png")
c.SaveAs("nVertices-MC-reweighted.eps")
hist_data.Draw()
c.SaveAs("nVertices-Data.png")
c.SaveAs("nVertices-Data.eps")
reweight = hist_data.Clone()
reweight.Divide(hist_mc)
for bin in range(reweight.GetNbinsX()+2):
  print str(bin)+": "+str(reweight.GetBinContent(bin))
